### ISSUE TITLE
静的解析ツールを導入する

### ISSUE THREAD

**Issue by ShSato4JPN** [ShSato4JPN/world-of-zono#13]
**Is your feature request related to a problem? Please describe.**
開発効率の向上を図り、静的解析ツールを導入する。

**Describe the solution you'd like**
eslint をインスールして、プロジェクトの root に .eslintrc.json ファイルを作成する。

**Additional context**
- 基本は [ESlint](https://eslint.org/docs/latest/user-guide/configuring/configuration-files) に記述されている内容をベースに設定。
- Next.js の基本設定を適用するために `next/core-web-vitals` を設定。
-  `react-hooks/exhaustive-deps` を rule に追加。

```
{
  "root": true,
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "next/core-web-vitals"
  ],
  "plugins": ["react", "@typescript-eslint"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": ["./tsconfig.json"] },
  "overrides": [],
  "ignorePatterns": ["/node_modules/", "/dist/"],
  "rules": {
    "react-hooks/exhaustive-deps": [
      "error",
      {
        "enableDangerousAutofixThisMayCauseInfiniteLoops": true
      }
    ]
  }
}
```
- react-hooks/exhaustive-deps
    > React が推奨しているルール

**Comment by piro0919** [comment]
@ShSato4JPN 

以下の導入も考慮してみてください。 👀 

- [eslint-config-next](https://nextjs.org/docs/basic-features/eslint)

また追加でこの設定を入れると実装が楽になるので個人的にはオススメです。 👍 

https://github.com/piro0919/kk-web3/blob/2296a938457210add53b83e2428c7a604dc0cbf2/.eslintrc.json#L118-L123

**Comment by ShSato4JPN** [comment]
@piro0919 

ご指摘ありがとうございます。
確認します！
