### ISSUE TITLE
stylelint についてまとめる

### ISSUE THREAD

**Issue by ShSato4JPN** [ShSato4JPN/world-of-zono#3]
**Is your feature request related to a problem? Please describe.**
stylelint についてまとめる

**Describe the solution you'd like**
マークダウンファイルにまとめる

**Additional context**
参考サイト
[StyleLint](https://stylelint.io/)

[.stylelintrc(Qitta)](https://qiita.com/takeshisakuma/items/a7a3b8cc0ce05422f686)

[prettier, eslint, stylelint について](https://rinoguchi.net/2021/12/prettier-eslint-stylelint.html)

**Comment by piro0919** [comment]
@ShSato4JPN 

以前にもお伝えしましたが、まずは公式サイトの記述のみを参考にしてみてください。 
個人のブログなどはエビデンスとしては不適格ですね。 🙅‍♂️

**Comment by ShSato4JPN** [comment]
かしこまりました🫡

**Comment by ShSato4JPN** [comment]
@piro0919 
別リポジトリに作成する issue を間違って本リポジトリに作成してしまったためクローズします。
