### ISSUE TITLE
Next で SCSS を使えるようにする

### ISSUE THREAD

**Issue by ShSato4JPN** [ShSato4JPN/world-of-zono#41]
**Is your feature request related to a problem? Please describe.**
本プロジェクトでは SCSS を採用するため、Next に Sass の設定を加える。

**Describe the solution you'd like**
公式ドキュメントを参考に `next.config.js` の設定を行う。

**Additional context**
[Sass Support](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support)

`next.config.js` に以下の設定を追加する。
```
const path = require('path')

module.exports = {
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')],
  },
}
```

**Comment by piro0919** [comment]
@ShSato4JPN 

今回のケースだと `includePaths` は以下のようにする必要があると思いますが、いかがでしょうか。 👀 

`includePaths: [path.join(__dirname, "src/styles")],`

**Comment by ShSato4JPN** [comment]
@piro0919 
ピロさんのご指摘通り、
next.config.js に設定を追加する必要はなく、Sass のインストールだけで対応が可能でした。

新たにブランチを切って対応いたしましたので、お手隙の際にご確認のほどよろしくお願いいたします。
