### ISSUE TITLE
.gitignore が Next.js の仕様にそっていない

### ISSUE THREAD

**Issue by piro0919** [ShSato4JPN/world-of-zono#54]
**Describe the bug**
.gitignore の内容が Next.js の cli によって生成された内容と異なる。

**Additional context**
てきとうなプロジェクトから、.gitignore の内容を持ってきちゃってください。 👍

**Comment by piro0919** [comment]
最初から変な内容になってますね、なぞ。 👀 

rel https://github.com/ShSato4JPN/world-of-zono/pull/6/files#

**Comment by ShSato4JPN** [comment]
@piro0919 
issue を立てていただきありがとうございます🙇‍♂️
