### ISSUE TITLE
記事一覧ページ、記事ページを作成するにあたり必要なパッケージを導入する。

### ISSUE THREAD

**Issue by ShSato4JPN** [ShSato4JPN/world-of-zono#66]
**Is your feature request related to a problem? Please describe.**
記事一覧ページ、記事ページを作成するにあたり必要なパッケージ一式をインストールする。

**Describe the solution you'd like**
今回インストールするパッケージは以下の通り。
- [react-infinite-scroll-component](https://www.npmjs.com/package/react-infinite-scroll-component)
> 無限スクロールの実装を簡易化するパッケージ。
- [react-markdown](https://www.npmjs.com/package/react-markdown)
>コンポーネントにマークダウンの記述を可能とするパッケージ。
- [swr](https://swr.vercel.app/ja)
>データ取得時の非同期処理の管理とキャッシュ管理を行うパッケージ。
- [@next/font](https://www.npmjs.com/package/@next/font)
>Next にてフォントの変更を行う際に使用するパッケージ。
- [react-loader-spinner](https://www.npmjs.com/package/react-loader-spinner)
>無限スクロールのデータ更新時に表示するアニメーションを担ってくれるパッケージ。

**Additional context**
上のパッケージは全て `dependencies` にインストールする。

**Comment by piro0919** [comment]
@ShSato4JPN 

@next/font は next のバージョンによっては deprecated している可能性もあるので、頭の片隅に置いておいてもらえればと。
