### ISSUE TITLE
モジュールのインポート時に絶対パスによる参照を有効化する

### ISSUE THREAD

**Issue by ShSato4JPN** [ShSato4JPN/world-of-zono#7]
**Is your feature request related to a problem? Please describe.**
以下の 2 つの理由から、絶対パスでの参照を有効化する。
- 相対パスによるモジュールのインポートはコードの可読性が低下するため。
- ファイルパスの変更時にも柔軟に対応できるような設計にするため。

**Describe the solution you'd like**
- src フォルダを追加後、tsconfig.json の設定を変更する。

**Additional context**
絶対パス参照を有効化するため、以下の作業を行う。
- プロジェクトの root に src フォルダを作成する。
- pages、styles フォルダを src フォルダ内に移動する。
- tsconfig.json に baseUrl の設定を追加する。

■ 追加内容
```
"baseUrl": "src"
```

**Comment by piro0919** [comment]
@ShSato4JPN 

Assignees を設定しましょう！

**Comment by ShSato4JPN** [comment]
@piro0919 

すみません、忘れていました。。
追加しましたので、お手隙の際にご確認よろしくお願いします。
